export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_ERROR = "USER_ERROR"


export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS"
export const CUSTOMER_ERROR = "CUSTOMER_ERROR"

